import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Footer from "@/components/Footer";
import TopBar from "@/components/TopBar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const basuru = localFont({
  src: "./../fonts/FMBasuru x.ttf",
  variable: "--font-basuru",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${basuru.variable}`}>
        <TopBar />
        <div className="  flex w-full min-h-[85vh] items-center justify-center text-2xl text-center sm:hidden">
          Can not use with mobile phones
        </div>
        <div className="max-sm:hidden">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
